install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb  
  - sudo dpkg -i /tmp/hugo.deb

script:
  - git clone -b master git@github.com:AlvaroGarciaJaen/alvarogarciajaen.github.io.git public
  - cd alvarogarciajaen.github.io
  - git clone -b master git@github.com:AlvaroGarciaJaen/hugo-theme-m10c.git themes/m10c
  - HUGO_ENV=production hugo -d ~/public
  - git config credential.helper 'cache --timeout=120'
  - git config user.email "deploy@alvaro.network"
  - git config user.name "Deployment Bot"
  - git add .
  - git commit --allow-empty -m "Trigger deployment"
  - git push -q git@github.com:AlvaroGarciaJaen/alvarogarciajaen.github.io.git master



deploy:
  - provider: script
    script: id
    skip_cleanup: true
    on:
      branch: source # or master if you are using the two-repository approach
