version: 2.0

jobs:
    build:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/alvarogarciajaen.github.io
        branches:
            only: 
                - source
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "27:e8:68:b4:35:ef:35:98:12:a4:a0:53:c0:01:f6:27"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b master git@github.com:AlvaroGarciaJaen/alvarogarciajaen.github.io.git public
            - run:
                name: Get theme
                working_directory: ~/alvarogarciajaen.github.io
                command: git clone -b master git@github.com:AlvaroGarciaJaen/hugo-theme-m10c.git themes/m10c
            - run:
                name: Generate site
                working_directory: ~/alvarogarciajaen.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "deploy@alvaro.network"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:AlvaroGarciaJaen/alvarogarciajaen.github.io.git master
